---
# dnf update
- name: dnf update 
  dnf:
    name: "*"
    state: latest

# Development tools の導入
- name: dnf yum groupinstall Development tools
  dnf:
    name: "@Development tools"
    state: latest

# dnf キャッシュの削除
- name: dnf clean packages
  shell: dnf clean packages

# epel インストール
- name: install epel-release
  dnf:
    name: epel-release
    state: latest

# Permissive SELinux
- name: permissive selinux
  selinux:
    state: permissive
    policy: targeted

# firewalld を無効化
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

# 追加パッケージ導入
- name: add operation packages
  yum:
    name:
      - net-tools
      - nmap
      - vim
      - bind-utils
      - telnet
      - wget
      - dstat
      - unzip
      - zip
      - etckeeper
      - postfix
    state: present

# postfix 起動
- name: start postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

# hostname 変更
- name: change hostname
  hostname: name="{{ inventory_hostname }}"

# sysctl 変更
- name: set kernel parameters to sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'net.core.somaxconn',value: '1024' }
    - { name: 'net.core.netdev_max_backlog',value: '5000' }
    - { name: 'net.core.rmem_max',value: '16777216' }
    - { name: 'net.core.wmem_max',value: '16777216' }
    - { name: 'net.ipv4.tcp_wmem',value: '4096 12582912 16777216' }
    - { name: 'net.ipv4.tcp_rmem',value: '4096 12582912 16777216' }
    - { name: 'net.ipv4.tcp_max_syn_backlog',value: '8096' }
    - { name: 'net.ipv4.tcp_slow_start_after_idle',value: '0' }
    - { name: 'net.ipv4.tcp_tw_reuse',value: '1' }
    - { name: 'net.ipv4.ip_local_port_range',value: '10240 65535' }
    - { name: 'net.ipv4.tcp_timestamps',value: '0' }
    - { name: 'vm.swappiness',value: '10' }

# limits_conf 変更
- name: change ulimit to limits.conf
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: nofile
    value: 65536
  with_items:
    - { domain: 'root' ,limit_type: 'soft' }
    - { domain: 'root' ,limit_type: 'hard' }
    - { domain: '*' ,limit_type: 'soft' }
    - { domain: '*' ,limit_type: 'hard' }

# timezone 変更
- name: change timezone Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# history 時刻表示追加
- name: add histry_time
  lineinfile:
     dest=/root/.bashrc
     line="HISTTIMEFORMAT='%Y-%m-%dT%T%z '"

- include_tasks: host_change.yml
- include_tasks: etckeeper_commit.yml
